name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag dockerimage:$(date +%s)

    - name: Tag the Docker image
      run: docker tag dockerimage:$(date +%s) vladadevops/python-image:latest

    - name: Push the Docker image to DockerHub
      run: docker push vladadevops/python-image:latest
